---
title: "Multiple Regression"
author: "Devan Becker"
format: live-html
engine: knitr
webr:
  packages:
    - ggplot2
    - broom
    - dplyr
    - palmerpenguins
  render-df: paged-table
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

## Load the Data

As usual, load all packages at the start of your document so that everyone knows what packages they'll need to install.

Technical note: R version 4.5 includes the `penguins` data as part of the default installation, but with different column names. So that we're all on the same page, we'll use the `palmerpenguins` package.

```{webr}
library(ggplot2)
theme_set(theme_bw())
#library(patchwork)
library(broom)
library(dplyr)
library(palmerpenguins)

data(penguins)
head(penguins)
```

## Basic Exploratory Plots

```{webr}
gg1 <- ggplot(data = penguins) +
    aes(x = flipper_length_mm, y = body_mass_g) +
    geom_point(na.rm = TRUE) +
    geom_smooth(
        method = "lm", formula = y ~ x, se = FALSE,
        na.rm = TRUE
    )

gg2 <- ggplot(data = penguins) +
    aes(x = bill_length_mm, y = body_mass_g) +
    geom_point(na.rm = TRUE) +
    geom_smooth(
        method = "lm", formula = y ~ x, se = FALSE
        na.rm = TRUE
    )

gg1
gg2
```

## Model Fitting!

Here's some code to fit a simple linear regression model to the data. Add some predictors and see what happens!

- How does the $R^2$ value change as you add more predictors?
- What happens to the coefficient estimates?
- What happens to the significance of the coefficients?

Keep track of this with pen and paper (or, for an extra challenge, keep track in R).

```{webr}
lm_bill_dep <- lm(body_mass_g ~ bill_depth_mm, data = penguins)

cat("Summary statistics:\n")
glance(lm_bill_dep)

cat("Coefficients:\n")
tidy(lm_bill_dep)

```


## Playground

Time permitting, I'll use this code chunk in lecture. Feel free to use it for whatever you want!

```{webr}

```
